import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffc885",
        background: "#060e20",
        "on-secondary-container": "#fff6f0",
        "outline-variant": "#40485d",
        "on-primary-fixed": "#00452d",
        "on-secondary-fixed-variant": "#724700",
        primary: "#69f6b8",
        "tertiary-fixed-dim": "#ff7986",
        "surface-bright": "#1f2b49",
        "on-tertiary-container": "#100001",
        "tertiary-fixed": "#ff9099",
        "error-dim": "#d7383b",
        "tertiary-container": "#fc4563",
        "on-primary-container": "#002919",
        "on-background": "#dee5ff",
        "secondary-fixed-dim": "#ffb554",
        "surface-container-highest": "#192540",
        "primary-fixed-dim": "#58e7ab",
        "on-error": "#490006",
        "on-secondary": "#4a2c00",
        "error-container": "#9f0519",
        "inverse-on-surface": "#4d556b",
        "secondary-container": "#855300",
        "on-surface-variant": "#a3aac4",
        "on-secondary-fixed": "#4c2e00",
        "surface-tint": "#69f6b8",
        "on-primary": "#005a3c",
        "surface-variant": "#192540",
        "on-tertiary": "#490010",
        "inverse-surface": "#faf8ff",
        "surface-dim": "#060e20",
        "primary-dim": "#58e7ab",
        "inverse-primary": "#006d4a",
        "surface-container": "#0f1930",
        "on-tertiary-fixed": "#39000b",
        "primary-container": "#06b77f",
        surface: "#060e20",
        "on-error-container": "#ffa8a3",
        outline: "#6d758c",
        error: "#ff716c",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#69f6b8",
        secondary: "#f8a010",
        "on-surface": "#dee5ff",
        "surface-container-high": "#141f38",
        "on-primary-fixed-variant": "#006544",
        "tertiary-dim": "#ff6f7e",
        "secondary-dim": "#e79400",
        "on-tertiary-fixed-variant": "#780021",
        tertiary: "#ff6f7e",
        "surface-container-low": "#091328",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [forms, containerQueries],
};

